Explicit coercion of offset / bump version
refs OUT-1415

notes:
This avoids the following error:
Implicit numeric calculations on a duration are getting changed in Rails 5.1 -
e.g. `240 / 2.minutes` will return `120` instead of `2` - so please make the
duration explicit with to_i
TypeError: ActiveSupport::Duration can't be coerced into Integer

test plan:
  - build gem
  - install locally
  - using credentials from the confluence page "Academic Benchmark v3 credentials",
    use the api to list authorities, and confirm that the above error doesn't occur

Change-Id: Ib441ad68b171e9d564c4a88fbf958984a62aa585
Reviewed-on: https://gerrit.instructure.com/122432
Tested-by: Jenkins
Reviewed-by: Michael Brewer-Davis <mbd@instructure.com>
Product-Review: Michael Brewer-Davis <mbd@instructure.com>
QA-Review: Michael Brewer-Davis <mbd@instructure.com>